name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v4
        with:
          project: GoogleInputTools.xcodeproj
          scheme: GoogleInputTools
          configuration: Debug
          arch: ${{ matrix.arch }}
          action: build

  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        uses: sersoft-gmbh/xcodebuild-action@v4
        with:
          project: GoogleInputTools.xcodeproj
          scheme: GoogleInputToolsTests
          configuration: Debug
          destination: platform=macOS
          action: test
